### ISSUE TITLE
User Review

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/draft-guide-microprofile-rest-client#28]
Copied from User Review: 

1. The git clone link provided in the guide requires username and password. I think that's because that repo is not public yet, but just letting you know.
 
2. When I run `mvn install` in the finish folder, the link http://localhost:9080/inventory/systems/{hostname} produces an error, I guess that is normal because the hostname is not specified at this point, but just letting you know. Here is the error:
 
Exception thrown by application class 'java.net.URI.create:852'
java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://{hostname}:9080/system
at java.net.URI.create(URI.java:852)
at org.apache.cxf.microprofile.client.MicroProfileClientFactoryBean.createClientProxy(MicroProfileClientFactoryBean.java:98)
at [internal classes]
at io.openliberty.guides.inventory.InventoryManager.getPropertiesWithGivenHostName(InventoryManager.java:76)
at io.openliberty.guides.inventory.InventoryManager.get(InventoryManager.java:43)
at io.openliberty.guides.inventory.InventoryManager$Proxy$_$$_WeldClientProxy.get(Unknown Source)
at io.openliberty.guides.inventory.InventoryResource.getPropertiesForHost(InventoryResource.java:41)
at io.openliberty.guides.inventory.InventoryResource$Proxy$_$$_WeldClientProxy.getPropertiesForHost(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:646)
at [internal classes]
Caused by: java.net.URISyntaxException: Illegal character in authority at index 7: http://{hostname}:9080/system
at java.net.URI$Parser.fail(URI.java:2848)
at java.net.URI$Parser.parseAuthority(URI.java:3186)
at java.net.URI$Parser.parseHierarchical(URI.java:3097)
at java.net.URI$Parser.parse(URI.java:3053)
at java.net.URI.(URI.java:588)
at java.net.URI.create(URI.java:850)
... 13 more
 
Not sure if this is intended.
 
The link http://{hostname}:9080/system/properties does not work. I guess, also because the hostname is not specified. Both of these worked for me once I worked through the instructions for the start folder.
 
 
The rest of the guide works with no issues :)
 
 
Cheers,
Anna

**Comment by JunyiSun** [comment]
Fixed by #26
